apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8069
    targetPort: 8069
    nodePort: 30069

    
  - name: longpolling
    protocol: TCP
    port: 8072
    targetPort: 8072
    nodePort: 30072
  selector:
    app: odoo